/* AUTO-GENERATED FILE. DO NOT MODIFY !!!
*
* This config file is automatically generated by build system.
* It should not be modified by hand.
*/

#ifndef OPENSDK_CONFIG_H
#define OPENSDK_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#define OPEN_VERSION "v1.6.0"
#define OPEN_COMMIT "0f2c299892c9111b71800068889b1f3c887af1c0"
#define PLATFORM_NAME "T5AI"
#define PLATFORM_COMMIT "7321a15f7f3f9c9419e165304ac92135bbaf4e30"
#define PLATFORM_CHIP "T5AI"
#define PLATFORM_BOARD "TUYA_T5AI_BOARD"

//
// configure project
//
#define PROJECT_NAME "Tuya95"
#define PROJECT_VERSION "1.0.0"
#define PROJECT_FRAMEWORK_BASE 1
// CONFIG_PROJECT_FRAMEWORK_ARDUINO is not set
#define FRAMEWORK_CHOICE "base"
// end of configure project

#define BOARD_ENABLE_LINUX 1
#define BOARD_ENABLE_T2 1
#define BOARD_ENABLE_T3 1
#define BOARD_ENABLE_T5AI 1
#define BOARD_ENABLE_ESP32 1
#define BOARD_ENABLE_LN882H 1
#define BOARD_ENABLE_BK7231X 1
// CONFIG_BOARD_CHOICE_LINUX is not set
#define PLATFORM_CHOICE "T5AI"
#define LITTLE_END 1
#define ENABLE_WIFI 1
#define ENABLE_BLUETOOTH 1
#define ENABLE_GPIO 1
#define ENABLE_I2C 1
#define ENABLE_SPI 1
#define ENABLE_PWM 1
#define ENABLE_UART 1
#define ENABLE_EXT_RAM 1
#define MBEDTLS_CONFIG_FILE "tuya_tls_config.h"
#define OPERATING_SYSTEM 98
#define CHIP_CHOICE "T5AI"
#define BOARD_CHOICE "TUYA_T5AI_BOARD"
#define BOARD_CONFIG 1
#define AUDIO_CODEC_NAME "audio"
#define BUTTON_NAME "button1"
// CONFIG_ENABLE_CAMERA is not set
// CONFIG_BOARD_CHOICE_T2 is not set
#define ENABLE_ADC 1
#define ENABLE_TIMER 1
#define ENABLE_WATCHDOG 1
// CONFIG_BOARD_CHOICE_T3 is not set
#define ENABLE_HCI 1
#define ENABLE_RTC 1
#define ENABLE_FLASH 1
#define TUYA_FLASH_TYPE_MAX_PARTITION_NUM 10
#define ENABLE_PM 1
#define ENABLE_WAKEUP 1
#define ENABLE_PINMUX 1
#define BOARD_CHOICE_T5AI 1
#define PLATFORM_T5 1
#define ENABLE_BIG_CORE 1
#define ENABLE_QSPI 1
#define ENABLE_MCU8080 1
#define ENABLE_TOUCH 1
#define ENABLE_MEDIA 1
#define ENABLE_DVP 1
#define ENABLE_DMA2D 1
#define ENABLE_RGB 1
#define ENABLE_PIN2FUNC 1
#define ENABLE_SMP 1
#define ENABLE_T5AI_OS_SERVICE 1
#define BOARD_CHOICE_TUYA_T5AI_BOARD 1
// CONFIG_TUYA_T5AI_BOARD_VERSION_101 is not set
#define TUYA_T5AI_BOARD_VERSION_102 1
#define TUYA_T5AI_BOARD_EX_MODULE_NONE 1
// CONFIG_TUYA_T5AI_BOARD_EX_MODULE_35565LCD is not set
// CONFIG_TUYA_T5AI_BOARD_EX_MODULE_EYES is not set
// CONFIG_TUYA_T5AI_BOARD_EX_MODULE_096_OLED is not set
// CONFIG_BOARD_CHOICE_TUYA_T5AI_EVB is not set
// CONFIG_BOARD_CHOICE_TUYA_T5AI_CORE is not set
// CONFIG_BOARD_CHOICE_T5AI_MINI is not set
// CONFIG_BOARD_CHOICE_T5AI_MOJI_1_28 is not set
// CONFIG_BOARD_CHOICE_TUYA_T5AI_POCKET is not set
// CONFIG_BOARD_CHOICE_ATK_T5AI_MINI_BOARD is not set
// CONFIG_BOARD_CHOICE_WAVESHARE_T5AI_TOUCH_AMOLED_1_75 is not set
// CONFIG_BOARD_CHOICE_T5AI_OTTO is not set
// CONFIG_BOARD_CHOICE_TUYA_T5AI_PIXEL is not set
// CONFIG_BOARD_CHOICE_TUYA_T5AI_DESKTOP_ROBOT is not set
// CONFIG_BOARD_CHOICE_TUYA_T5AI_DOG is not set
// CONFIG_BOARD_CHOICE_TUYA_T5AI_EINK_NFC is not set
// CONFIG_BOARD_CHOICE_ESP32 is not set
#define DISPLAY_NAME "display"
// CONFIG_BOARD_CHOICE_LN882H is not set
// CONFIG_BOARD_CHOICE_BK7231X is not set

//
// configure tuyaopen
//
// CONFIG_ENABLE_SERIAL_CLI_CMD is not set
#define SERIAL_CLI_STACK_SIZE 3072

//
// configure tuya cloud service
//
#define TUYA_SECURITY_LEVEL 1
#define ENABLE_BT_SERVICE 1
#define ENABLE_BT_NETCFG 1
#define ENABLE_BT_CTRL 1
#define BT_ADV_INTERVAL_MIN 30
#define BT_ADV_INTERVAL_MAX 60
#define BT_REMOTE_CTRL_SCAN_INTERVAL 30
#define BT_REMOTE_CTRL_SCAN_WINDOWS 10
#define ENABLE_NIMBLE 1
#define TUYA_HS_BLE_HOST_TASK_PRIORITY 9
#define TUYA_HS_BLE_HOST_STACK_SIZE 5120
// end of configure tuya cloud service

//
// configure tuya AI
//

//
// AI Agent Config
//
#define AI_INPUT_STACK_SIZE 4608
#define AI_INPUT_RINGBUF_SIZE 65536
#define AI_INPUT_BUF_SIZE 6144
#define AI_OUTPUT_STACK_SIZE 4096
#define AI_OUTPUT_RINGBUF_SIZE 65536
#define AI_OUTPUT_BUF_SIZE 5120
// end of AI Agent Config

//
// AI Protocol Config
//
#define ENABLE_AI_MONITOR 1
#define AI_MAX_FRAGMENT_LENGTH 10240
// CONFIG_ENABLE_AI_PROTO_DEBUG is not set
#define AI_BIZ_TASK_DELAY 10
#define AI_SESSION_MAX_NUM 2
#define AI_BIZ_MAX_NUM 5
#define AI_MAX_ATTR_NUM 10
#define AI_PING_TIMEOUT 6
#define AI_HEARTBEAT_INTERVAL 120
#define AI_PACKET_SECURITY_LEVEL 4
#define AI_CLIENT_STACK_SIZE 4096
#define AI_READ_SOCKET_BUF_SIZE 0
#define AI_WRITE_SOCKET_BUF_SIZE 8192
#define AI_DL_IMAGE_UNIT_SIZE 4096
#define AI_HEAP_IN_PSRAM 1
// CONFIG_AI_STACK_IN_PSRAM is not set
#define AI_SEND_PKT_TIMEOUT 6
#define AI_VERSION 1
// end of AI Protocol Config

#define ENABLE_TUYA_CODEC 1
// CONFIG_ENABLE_TUYA_CODEC_OPUS is not set
// CONFIG_ENABLE_TUYA_CODEC_SPEEX is not set
// end of configure tuya AI

// CONFIG_ENABLE_AI_PLAYER is not set

//
// configure enable/disable liblwip
//
// CONFIG_ENABLE_LIBLWIP is not set
// end of configure enable/disable liblwip

//
// configure mbedtls
//
// CONFIG_ENABLE_MBEDTLS_DEBUG is not set
#define ENABLE_MBEDTLS_SSL_MAX_CONTENT_LEN 4096
// CONFIG_ENABLE_CUSTOM_CONFIG is not set
// end of configure mbedtls

//
// configure system parameter
//
#define STACK_SIZE_TIMERQ 4096
#define STACK_SIZE_WORK_QUEUE 5120
#define MAX_NODE_NUM_WORK_QUEUE 100
#define STACK_SIZE_MSG_QUEUE 4096
#define MAX_NODE_NUM_MSG_QUEUE 100
// end of configure system parameter

#define ENABLE_LIBLVGL 1
// CONFIG_LVGL_VERSION_8 is not set
#define LVGL_VERSION_9 1
// CONFIG_ENABLE_LVGL_OS_FREERTOS is not set
#define LVGL_ENABLE_TP 1
// CONFIG_ENABLE_LVGL_DEMO is not set
// CONFIG_ENABLE_LVGL_MONITOR is not set
// CONFIG_ENABLE_LVGL_ENCODER is not set
// CONFIG_ENABLE_LVGL_LODEPNG is not set
// CONFIG_ENABLE_LVGL_DUAL_DISP_BUFF is not set
#define LV_DRAW_BUF_PROPORTION_10 1
// CONFIG_LV_DRAW_BUF_PROPORTION_5 is not set
#define LV_DRAW_BUF_PARTS 10

//
// LVGL Font Configuration
//

//
// Montserrat Fonts with ASCII range (bpp = 4)
//
// CONFIG_LV_FONT_MONTSERRAT_8 is not set
// CONFIG_LV_FONT_MONTSERRAT_10 is not set
// CONFIG_LV_FONT_MONTSERRAT_12 is not set
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 1
// CONFIG_LV_FONT_MONTSERRAT_18 is not set
// CONFIG_LV_FONT_MONTSERRAT_20 is not set
// CONFIG_LV_FONT_MONTSERRAT_22 is not set
#define LV_FONT_MONTSERRAT_24 1
// CONFIG_LV_FONT_MONTSERRAT_26 is not set
// CONFIG_LV_FONT_MONTSERRAT_28 is not set
// CONFIG_LV_FONT_MONTSERRAT_30 is not set
// CONFIG_LV_FONT_MONTSERRAT_32 is not set
// CONFIG_LV_FONT_MONTSERRAT_34 is not set
// CONFIG_LV_FONT_MONTSERRAT_36 is not set
// CONFIG_LV_FONT_MONTSERRAT_38 is not set
// CONFIG_LV_FONT_MONTSERRAT_40 is not set
// CONFIG_LV_FONT_MONTSERRAT_42 is not set
// CONFIG_LV_FONT_MONTSERRAT_44 is not set
// CONFIG_LV_FONT_MONTSERRAT_46 is not set
// CONFIG_LV_FONT_MONTSERRAT_48 is not set

//
// Special Fonts
//
// CONFIG_LV_FONT_MONTSERRAT_28_COMPRESSED is not set
// CONFIG_LV_FONT_DEJAVU_16_PERSIAN_HEBREW is not set
// CONFIG_LV_FONT_SIMSUN_16_CJK is not set

//
// Pixel Perfect Monospace Fonts
//
#define LV_FONT_UNSCII_8 1
#define LV_FONT_UNSCII_16 1
// end of LVGL Font Configuration

//
// configure device driver
//
#define ENABLE_BUTTON 1
#define BUTTION_STACK_SIZE 2048
// CONFIG_ENABLE_BUTTON_2 is not set
#define ENABLE_LED 1
#define LED_NUM 1
#define LED_NAME "led"
#define ENABLE_AUDIO_CODECS 1
#define AUDIO_CODECS_NUM 1
#define ENABLE_AUDIO_AEC 1
#define ENABLE_DISPLAY 1
// CONFIG_ENABLE_DISPLAY_2 is not set
#define ENABLE_TP 1
// CONFIG_ENABLE_ENCODER is not set
// CONFIG_ENABLE_JOYSTICK is not set
// CONFIG_ENABLE_PMIC is not set
// CONFIG_ENABLE_IR is not set
// CONFIG_ENABLE_LEDS_PIXEL is not set
// CONFIG_ENABLE_IMU is not set
// end of configure device driver

// CONFIG_ENABLE_TUYA_P2P is not set
// CONFIG_ENABLE_MICROPYTHON is not set
// end of configure tuyaopen


#ifdef __cplusplus
}
#endif

#endif  // OPENSDK_CONFIG_H


